#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Point3 { pub x: f64, pub y: f64, pub z: f64 }
impl Point3 { fn add(self, o: Self)->Self{Self{x:self.x+o.x,y:self.y+o.y,z:self.z+o.z}} }
#[derive(Clone, Copy, Debug, PartialEq)] pub struct BoundingBox3{pub min:Point3,pub max:Point3}
#[derive(Clone, Copy, Debug, PartialEq)] pub enum NurbsSurfaceError{NonFinite,InvalidDegree,InvalidControlPointCount,InvalidWeightCount,InvalidWeight,InvalidKnotCount,KnotsMustBeNondecreasing,NotClamped,InvalidDomain,OutOfDomain,Degenerate,ZeroProjectiveWeight,Overflow}
#[derive(Clone, Debug, PartialEq)] pub struct NurbsSurface2D{pub degree_u:usize,pub degree_v:usize,pub control_points:Vec<Point3>,pub weights:Vec<f64>,pub knots_u:Vec<f64>,pub knots_v:Vec<f64>}
impl NurbsSurface2D{
 pub fn new(du:usize,dv:usize,p:Vec<Point3>,w:Vec<f64>,ku:Vec<f64>,kv:Vec<f64>)->Self{Self{degree_u:du,degree_v:dv,control_points:p,weights:w,knots_u:ku,knots_v:kv}}
 pub fn validate(&self)->Result<(),NurbsSurfaceError>{if self.degree_u==0||self.degree_v==0{return Err(NurbsSurfaceError::InvalidDegree)}let uc=self.control_count_u();let vc=self.control_count_v();if uc<self.degree_u+1||vc<self.degree_v+1{return Err(NurbsSurfaceError::InvalidControlPointCount)}if uc*vc!=self.control_points.len(){return Err(NurbsSurfaceError::InvalidControlPointCount)}if self.weights.len()!=self.control_points.len(){return Err(NurbsSurfaceError::InvalidWeightCount)}if self.knots_u.len()!=uc+self.degree_u+1||self.knots_v.len()!=vc+self.degree_v+1{return Err(NurbsSurfaceError::InvalidKnotCount)}if self.control_points.iter().any(|p|!p.x.is_finite()||!p.y.is_finite()||!p.z.is_finite()){return Err(NurbsSurfaceError::NonFinite)}if self.weights.iter().any(|w|!w.is_finite()){return Err(NurbsSurfaceError::NonFinite)}if self.weights.iter().any(|w|*w<=0.0){return Err(NurbsSurfaceError::InvalidWeight)}validate_knots(&self.knots_u)?;validate_knots(&self.knots_v)?;validate_clamped(&self.knots_u,self.degree_u,uc)?;validate_clamped(&self.knots_v,self.degree_v,vc)?;Ok(())}
 pub fn parameter_domain(&self)->Result<(f64,f64,f64,f64),NurbsSurfaceError>{self.validate()?;Ok((self.knots_u[self.degree_u],self.knots_u[self.control_count_u()],self.knots_v[self.degree_v],self.knots_v[self.control_count_v()]))}
 pub fn point_at(&self,u:f64,v:f64)->Result<Point3,NurbsSurfaceError>{self.validate()?;if !u.is_finite()||!v.is_finite(){return Err(NurbsSurfaceError::NonFinite)}let(a,b,c,d)=self.parameter_domain_unchecked();if u<a||u>b||v<c||v>d{return Err(NurbsSurfaceError::OutOfDomain)}let h=self.eval_h(u,v);dehom(h)}
 pub fn control_hull_bounds(&self)->Result<BoundingBox3,NurbsSurfaceError>{self.validate()?;let min=Point3{x:self.control_points.iter().map(|p|p.x).fold(f64::INFINITY,f64::min),y:self.control_points.iter().map(|p|p.y).fold(f64::INFINITY,f64::min),z:self.control_points.iter().map(|p|p.z).fold(f64::INFINITY,f64::min)};let max=Point3{x:self.control_points.iter().map(|p|p.x).fold(f64::NEG_INFINITY,f64::max),y:self.control_points.iter().map(|p|p.y).fold(f64::NEG_INFINITY,f64::max),z:self.control_points.iter().map(|p|p.z).fold(f64::NEG_INFINITY,f64::max)};Ok(BoundingBox3{min,max})}
 pub fn translated(&self,dx:f64,dy:f64,dz:f64)->Result<Self,NurbsSurfaceError>{self.validate()?;if !dx.is_finite()||!dy.is_finite()||!dz.is_finite(){return Err(NurbsSurfaceError::NonFinite)}let d=Point3{x:dx,y:dy,z:dz};let p=self.control_points.iter().map(|p|p.add(d)).collect();Ok(Self::new(self.degree_u,self.degree_v,p,self.weights.clone(),self.knots_u.clone(),self.knots_v.clone()))}
 fn control_count_u(&self)->usize{self.knots_u.len().saturating_sub(self.degree_u+1)}fn control_count_v(&self)->usize{self.knots_v.len().saturating_sub(self.degree_v+1)}fn parameter_domain_unchecked(&self)->(f64,f64,f64,f64){(self.knots_u[self.degree_u],self.knots_u[self.control_count_u()],self.knots_v[self.degree_v],self.knots_v[self.control_count_v()])}
 fn eval_h(&self,u:f64,v:f64)->H{let uc=self.control_count_u();let vc=self.control_count_v();let us=span(u,self.degree_u,&self.knots_u,uc);let mut rows=Vec::with_capacity(vc);for j in 0..vc{let mut w=Vec::with_capacity(self.degree_u+1);for l in 0..=self.degree_u{let i=us-self.degree_u+l;let idx=i*vc+j;let p=self.control_points[idx];let q=self.weights[idx];w.push(H{xw:p.x*q,yw:p.y*q,zw:p.z*q,w:q});}rows.push(deboor(u,us,self.degree_u,&self.knots_u,&mut w));}let vs=span(v,self.degree_v,&self.knots_v,vc);let mut w=Vec::with_capacity(self.degree_v+1);for l in 0..=self.degree_v{w.push(rows[vs-self.degree_v+l]);}deboor(v,vs,self.degree_v,&self.knots_v,&mut w)}
}
#[derive(Clone,Copy)]struct H{xw:f64,yw:f64,zw:f64,w:f64}impl H{fn lerp(self,o:Self,a:f64)->Self{Self{xw:self.xw*(1.-a)+o.xw*a,yw:self.yw*(1.-a)+o.yw*a,zw:self.zw*(1.-a)+o.zw*a,w:self.w*(1.-a)+o.w*a}}}
fn deh(h:H)->Result<Point3,NurbsSurfaceError>{if [h.xw,h.yw,h.zw,h.w].iter().any(|x|!x.is_finite()){return Err(NurbsSurfaceError::Overflow)}if h.w<=0.{return Err(NurbsSurfaceError::ZeroProjectiveWeight)}let p=Point3{x:h.xw/h.w,y:h.yw/h.w,z:h.zw/h.w};if !p.x.is_finite()||!p.y.is_finite()||!p.z.is_finite(){Err(NurbsSurfaceError::Overflow)}else{Ok(p)}}
fn validate_knots(k:&[f64])->Result<(),NurbsSurfaceError>{if k.iter().any(|x|!x.is_finite()){return Err(NurbsSurfaceError::NonFinite)}if k.windows(2).any(|p|p[1]<p[0]){return Err(NurbsSurfaceError::KnotsMustBeNondecreasing)}Ok(())}
fn validate_clamped(k:&[f64],p:usize,n:usize)->Result<(),NurbsSurfaceError>{let s=k[p];let e=k[n];if e<=s{return Err(NurbsSurfaceError::InvalidDomain)}if !k[..=p].iter().all(|x|*x==s)||!k[n..].iter().all(|x|*x==e){return Err(NurbsSurfaceError::NotClamped)}Ok(())}
fn span(t:f64,p:usize,k:&[f64],n:usize)->usize{let last=n-1;if t>=k[n]{return last}if t<=k[p]{return p}let(mut lo,mut hi)=(p,n);let mut m=(lo+hi)/2;while t<k[m]||t>=k[m+1]{if t<k[m]{hi=m}else{lo=m};m=(lo+hi)/2}m}
fn deboor(t:f64,s:usize,p:usize,k:&[f64],w:&mut[H])->H{if p==0{return w[0]}for r in 1..=p{for j in (r..=p).rev(){let i=s-p+j;let den=k[i+p+1-r]-k[i];let a=if den==0.{0.}else{(t-k[i])/den};w[j]=w[j-1].lerp(w[j],a)}}w[p]}
#[cfg(test)]mod tests{use super::*;#[test]fn bilinear_patch(){let s=NurbsSurface2D::new(1,1,vec![Point3{x:0.,y:0.,z:0.},Point3{x:0.,y:1.,z:1.},Point3{x:1.,y:0.,z:2.},Point3{x:1.,y:1.,z:3.}],vec![1.;4],vec![0.,0.,1.,1.],vec![0.,0.,1.,1.]);let p=s.point_at(.25,.75).unwrap();assert!((p.z-1.25).abs()<1e-12)}}
