use crate::{IntersectionStatus, SurfaceIntersectionSegment};
use umlcad_v6_nurbs_surface_api::{NurbsSurface3DDefinition, ParameterPoint2, TrimLoop2D, TrimmedNurbsSurface3DDefinition};

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum IntersectionTrimError { NonFinite, InvalidSurface, InvalidIntersection, UnsupportedSurfaceFamily, EndpointsNotOnBoundary, DegenerateTrimRegion }
#[derive(Clone, Debug, PartialEq)]
pub struct PlanarIntersectionTrimResult { pub first_region: TrimmedNurbsSurface3DDefinition, pub second_region: TrimmedNurbsSurface3DDefinition }
#[derive(Clone, Copy)] struct Rectangle { u0:f64,u1:f64,v0:f64,v1:f64 }
fn signed_area2(points:&[ParameterPoint2])->f64{points.iter().zip(points.iter().cycle().skip(1)).take(points.len()).map(|(a,b)|a.u*b.v-b.u*a.v).sum()}
fn normalize_loop(mut points:Vec<ParameterPoint2>,tolerance:f64)->Option<TrimLoop2D>{if points.len()<3{return None;}let mut cleaned=Vec::with_capacity(points.len());for point in points.drain(..){if cleaned.last().is_none_or(|last:&ParameterPoint2|(last.u-point.u).hypot(last.v-point.v)>tolerance){cleaned.push(point);}}if cleaned.len()>1{let first=cleaned[0];let last=*cleaned.last()?;if(first.u-last.u).hypot(first.v-last.v)<=tolerance{cleaned.pop();}}if cleaned.len()<3||signed_area2(&cleaned).abs()<=tolerance*tolerance{return None;}if signed_area2(&cleaned)<0.0{cleaned.reverse();}Some(TrimLoop2D::new(cleaned))}
fn boundary(point:ParameterPoint2,rect:Rectangle,tolerance:f64)->bool{(point.u-rect.u0).abs()<=tolerance||(point.u-rect.u1).abs()<=tolerance||(point.v-rect.v0).abs()<=tolerance||(point.v-rect.v1).abs()<=tolerance}
fn side_value(a:ParameterPoint2,b:ParameterPoint2,p:ParameterPoint2)->f64{(b.u-a.u)*(p.v-a.v)-(b.v-a.v)*(p.u-a.u)}
fn clip_half_plane(polygon:&[ParameterPoint2],a:ParameterPoint2,b:ParameterPoint2,keep_positive:bool,tolerance:f64)->Vec<ParameterPoint2>{if polygon.is_empty(){return Vec::new();}let mut output=Vec::new();for i in 0..polygon.len(){let current=polygon[i];let previous=polygon[(i+polygon.len()-1)%polygon.len()];let current_value=side_value(a,b,current);let previous_value=side_value(a,b,previous);let current_inside=if keep_positive{current_value>=-tolerance}else{current_value<=tolerance};let previous_inside=if keep_positive{previous_value>=-tolerance}else{previous_value<=tolerance};if current_inside!=previous_inside{let denominator=previous_value-current_value;if denominator.abs()>f64::EPSILON{let t=previous_value/denominator;output.push(ParameterPoint2{u:previous.u+t*(current.u-previous.u),v:previous.v+t*(current.v-previous.v)});}}if current_inside{output.push(current);}}output}
pub fn split_planar_surface_by_intersection(surface:&NurbsSurface3DDefinition,segment:&SurfaceIntersectionSegment,tolerance:f64)->Result<PlanarIntersectionTrimResult,IntersectionTrimError>{if !tolerance.is_finite()||tolerance<0.0{return Err(IntersectionTrimError::NonFinite);}surface.validate().map_err(|_|IntersectionTrimError::InvalidSurface)?;if surface.degree_u!=1||surface.degree_v!=1||surface.count_u!=2||surface.count_v!=2||surface.weights.iter().any(|w|(*w-1.0).abs()>1e-14){return Err(IntersectionTrimError::UnsupportedSurfaceFamily);}let((u0,u1),(v0,v1))=surface.parameter_domain().map_err(|_|IntersectionTrimError::InvalidSurface)?;let rect=Rectangle{u0,u1,v0,v1};let a=ParameterPoint2{u:segment.start.first_uv.0,v:segment.start.first_uv.1};let b=ParameterPoint2{u:segment.end.first_uv.0,v:segment.end.first_uv.1};if ![a.u,a.v,b.u,b.v].iter().all(|x|x.is_finite()){return Err(IntersectionTrimError::NonFinite);}if !boundary(a,rect,tolerance)||!boundary(b,rect,tolerance){return Err(IntersectionTrimError::EndpointsNotOnBoundary);}if(a.u-b.u).hypot(a.v-b.v)<=tolerance.max(1e-12){return Err(IntersectionTrimError::InvalidIntersection);}let rectangle=vec![ParameterPoint2{u:u0,v:v0},ParameterPoint2{u:u1,v:v0},ParameterPoint2{u:u1,v:v1},ParameterPoint2{u:u0,v:v1}];let trim_tolerance=tolerance.max(1e-12);let first_loop=normalize_loop(clip_half_plane(&rectangle,a,b,true,tolerance),trim_tolerance).ok_or(IntersectionTrimError::DegenerateTrimRegion)?;let second_loop=normalize_loop(clip_half_plane(&rectangle,a,b,false,tolerance),trim_tolerance).ok_or(IntersectionTrimError::DegenerateTrimRegion)?;let first_region=TrimmedNurbsSurface3DDefinition::new(surface.clone(),vec![first_loop]);let second_region=TrimmedNurbsSurface3DDefinition::new(surface.clone(),vec![second_loop]);first_region.validate().map_err(|_|IntersectionTrimError::DegenerateTrimRegion)?;second_region.validate().map_err(|_|IntersectionTrimError::DegenerateTrimRegion)?;Ok(PlanarIntersectionTrimResult{first_region,second_region})}
pub fn split_planar_surface_from_intersection(surface:&NurbsSurface3DDefinition,status:IntersectionStatus,segments:&[SurfaceIntersectionSegment],tolerance:f64)->Result<PlanarIntersectionTrimResult,IntersectionTrimError>{if status!=IntersectionStatus::Unique||segments.len()!=1{return Err(IntersectionTrimError::InvalidIntersection);}split_planar_surface_by_intersection(surface,&segments[0],tolerance)}

#[cfg(test)]
mod tests{use super::*;use crate::{intersect_planar_nurbs_surfaces,Point3};fn horizontal()->NurbsSurface3DDefinition{NurbsSurface3DDefinition::new((1,1),vec![Point3{x:0.,y:0.,z:0.},Point3{x:0.,y:1.,z:0.},Point3{x:1.,y:0.,z:0.},Point3{x:1.,y:1.,z:0.}],vec![1.;4],(2,2),vec![0.,0.,1.,1.],vec![0.,0.,1.,1.])}fn crossing()->NurbsSurface3DDefinition{NurbsSurface3DDefinition::new((1,1),vec![Point3{x:.5,y:-1.,z:-1.},Point3{x:.5,y:-1.,z:1.},Point3{x:.5,y:2.,z:-1.},Point3{x:.5,y:2.,z:1.}],vec![1.;4],(2,2),vec![0.,0.,1.,1.],vec![0.,0.,1.,1.])}#[test]fn computed_intersection_drives_two_valid_trim_regions(){let base=horizontal();let hit=intersect_planar_nurbs_surfaces(&base,&crossing(),1e-10).unwrap();let result=split_planar_surface_from_intersection(&base,hit.status,&hit.segments,1e-10).unwrap();assert!(result.first_region.validate().is_ok());assert!(result.second_region.validate().is_ok());assert_eq!(result.first_region.loops.len(),1);assert_eq!(result.second_region.loops.len(),1);}#[test]fn interior_segment_cannot_be_promoted_to_surface_split(){let segment=SurfaceIntersectionSegment{start:crate::SurfaceIntersectionEndpoint{point:Point3{x:.25,y:.25,z:0.},first_uv:(.25,.25),second_uv:(.25,.25)},end:crate::SurfaceIntersectionEndpoint{point:Point3{x:.75,y:.75,z:0.},first_uv:(.75,.75),second_uv:(.75,.75)}};assert_eq!(split_planar_surface_by_intersection(&horizontal(),&segment,1e-10),Err(IntersectionTrimError::EndpointsNotOnBoundary));}}
