[package]
name = "umlcad-v6-occt-backend"
version = "0.1.0"
edition = "2021"
license = "MIT"
build = "build.rs"

[dependencies]
umlcad-v6-geometry-api = { path = "../geometry-api" }
umlcad-v6-freeform-api = { path = "../freeform-api" }
umlcad-v6-nurbs-surface-api = { path = "../nurbs-surface-api" }
umlcad-v6-mesh-api = { path = "../mesh-api" }
umlcad-v6-exchange-api = { path = "../exchange-api" }

[build-dependencies]
cmake = "0.1"
